### PR TITLE
Fix readme typo

### PR DESCRIPTION
**Pull request by GodfirstOnuoha**
Corrected some typo in day 6 README.md file
Fix issue #120

### CODE REVIEW

**Review by kodekage — APPROVED** [review]
Locating the typo is pretty difficult, next time don't delete the whole list, just remote the word/sentence.

**Comment by GodfirstOnuoha** [comment]
Alright, how do I remote the word/sentence?

**Comment by kodekage** [comment]
Just edit the specific area and git diff will detect it and point me to the edited area.

In your case the area you edited was so large and covered some places that needed no change

**Comment by GodfirstOnuoha** [comment]
Okay sir, noted.
Thanks

**Pull request merged**
