### PR TITLE
Create ugwulo-day2.md

### PR DESCRIPTION
**Pull request by ugwulo**

### CODE REVIEW

**Comment by ugwulo** [comment]
# Day 2

## Current Remotes
currentRemote

## New Remote
newRemote

## Pull Changes
pullChanges

## Push Changes
pushChanges

**Comment by ugwulo** [comment]
day 2 submission

**Review by prondubuisi — CHANGES_REQUESTED** [review]
Hello @ugwulo Your file has no content, can you please see how others did theirs? Add the screenshots to the readme you just created!

**Comment by prondubuisi** [comment]
Hello @ugwulo you don't have to close it. Just do a Git pull origin master, then add the requested changes and push. Thanks.

**Pull request closed without merging**
