### PR TITLE
Day 2 Challenge

### PR DESCRIPTION
**Pull request by GodfirstOnuoha**
Finished Day 2 Challenge

### CODE REVIEW

**Review by prondubuisi — APPROVED** [review]
This looks good @ChibuFirst. Just a pointer on making multiple  commits for one PR. You should ensure that each PR has just one commit, and in a situation where you have multiple commits you can use git rebase and git squash to combine it to 1 commit.

**Comment by GodfirstOnuoha** [comment]
Sir, I tried using `git rebase` and `git squash` but it said `git squash` is invalid

**Comment by prondubuisi** [comment]
Hello @ChibuFirst just google their usage.

**Comment by GodfirstOnuoha** [comment]
Ok sir, I will.
Thanks

**Pull request merged**
