### PR TITLE
my day2 challenge

### PR DESCRIPTION
**Pull request by darlcruz**
day2 done and i learnt a lot thou

### CODE REVIEW

**Comment by prondubuisi** [comment]
Can't merge bro, you have Almost one million commits
We should have a video call when you are free @darlcruz

**Comment by darlcruz** [comment]
the issue izit with day1 or day2?

**Comment by prondubuisi** [comment]
Both days.

**Comment by kodekage** [comment]
It will be best to close this PR.

@darlcruz **fork this repository** and don't clone directly (this should be the cause)

Looking to receive your new PR from a your forked repo

**Pull request closed without merging**
