### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by andemosa**
Day 1 task

### CODE REVIEW

**Review by prondubuisi — CHANGES_REQUESTED** [review]
Hello @andemosa Great work. Can you upload this images to Github and then add the links? that ensures that our project is not so heavy with lots of files. You can upload the image on a Github Issue and then copy the link, let me know if you need more help with this.

**Comment by prondubuisi** [comment]
Also if you can, make your commits single for  every pull request.

**Comment by prondubuisi** [comment]
Lastly treat you pull request naming like you would handle identifiers(variable names, class names etc) within your code. Your PR names should be very clear and explain what the PR does. Patch 1 is not explanatory, but something like Submit day 1 challenge is more explanatory.

**Comment by kodekage** [comment]
@andemosa are you having issues effecting the requested change?

**Pull request closed without merging**
