### PR TITLE
merge day 4 submission

### PR DESCRIPTION
**Pull request by ugwulo**

### CODE REVIEW

**Comment by prondubuisi** [comment]
hello @ugwulo your pull request has conflicts that should be resolved, do a `git pull --rebase origin master', if your origin points to https://github.com/fbdevcowerri/git-14days-challenge, you can see where your origin points to by running `git remote -v` If you use VScode it will also be easy to see incoming changes and merge them easily.

**Comment by ugwulo** [comment]
@prondubuisi how do I resolve this when my origin is pointing to "origin  https://github.com/ugwulo/git-14days-challenge.git"
and also how do I merge changes too and to where eaxctly. Thanks for your feedback.

**Comment by austitech** [comment]
> @prondubuisi how do I resolve this when my origin is pointing to "origin https://github.com/ugwulo/git-14days-challenge.git"
> and also how do I merge changes too and to where eaxctly. Thanks for your feedback.

To change your origin remote url use **git remote set-url origin https://GitHub.com/fbdevcowerri/git-14days-challenge**. 
verify the change using **git remote -v**

**Comment by prondubuisi** [comment]
Great Stuff @austitech. Way to go!

**Comment by austitech** [comment]
> Great Stuff @austitech. Way to go!

Thanks bro

**Comment by austitech** [comment]
> @prondubuisi how do I resolve this when my origin is pointing to "origin https://github.com/ugwulo/git-14days-challenge.git"
> and also how do I merge changes too and to where eaxctly. Thanks for your feedback.

For merging changes, you need to add another remote url with your name that points to your forked repo.  
## Example  
### add remote url for forked repo
git remote set-url ugwulo https://github.com/ugwulo/git-14days-challenge

### pull recent changes from origin before working on your task
git pull origin master

### good to pull recent changes from origin after completing your task
git pull origin master

### now push to your forked repo branch you added earlier
git push ugwulo master

### To create a pull request
Goto your forked repo and click on pull request.

**Comment by ugwulo** [comment]
thanks @austitech 
the conflicting file has been resolved @prondubuisi

**Pull request merged**
